config/routes.rb
Utransfer::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  post 'universities/universities_faculties'  => 'university#universities_faculties'

  post 'contact/email'  => 'contact#email'

  post 'offer/email'  => 'offer#email'

  post 'offer/additional'  => 'offer#additional'

  resources :essentials

  resources :testimonial

  resources :university

  root :to => 'home#index'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :personals
	has_many :testimonials

	default_scope :order => 'priority DESC'
end

app/models/essential.rb
class Essential < ActiveRecord::Base
	translates :topic

	has_many :essential_texts

	has_many :essential_translations
	accepts_nested_attributes_for :essential_translations

	default_scope :order => 'position ASC'

	validates :topic, :position, :presence => true
end

app/models/essential_text.rb
class EssentialText < ActiveRecord::Base
	translates :title, :text

	belongs_to :essential

	has_many :essential_text_translation
	accepts_nested_attributes_for :essential_text_translation

	validates :essential_id, :title, :text, :presence => true
end

app/models/experience_image.rb
class ExperienceImage < ActiveRecord::Base

	mount_uploader :image_file, ImageUploader

	belongs_to :testimonial
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base

	translates :desc, :name

	has_many :faculty_translation
	accepts_nested_attributes_for :faculty_translation

	belongs_to :university

	validates :name, :desc, :university_id, :presence => true

	def level_enum
    {:bsc => "BSc", :msc => "MSc", :phd => "PhD", :preschool => "Pre-school"}
  end

end

app/models/famous_graduate.rb
class FamousGraduate < ActiveRecord::Base

	translates :title

	has_many :famous_graduate_translation
	accepts_nested_attributes_for :famous_graduate_translation

	mount_uploader :image_file, FamousPersonUploader

	validates :name, :title, :university_id, :presence => true

	belongs_to :university

end

app/models/index_content.rb
class IndexContent < ActiveRecord::Base
	translates :intro, :basic_info, :famous_person_quote
end

app/models/living_cost.rb
class LivingCost < ActiveRecord::Base
end

app/models/media.rb
class Media < ActiveRecord::Base

	belongs_to :text_block

	mount_uploader :image_file, ImageUploader

	validates :image_file, :title, :presence => true

end

app/models/personal.rb
class Personal < ActiveRecord::Base
	belongs_to :university
	belongs_to :faculty
	belongs_to :country
end

app/models/process_flow.rb
class ProcessFlow < ActiveRecord::Base

	translates :text, :title

	has_many :process_flow_translation
	accepts_nested_attributes_for :process_flow_translation

	validates :title, :text, :position, :presence => true
	validates :position, :uniqueness => true

end

app/models/related_industry.rb
class RelatedIndustry < ActiveRecord::Base
	has_and_belongs_to_many :universities

	mount_uploader :image_file, IndustryUploader

	validates :name, :image_file, :presence => true

end

app/models/requirement.rb
class Requirement < ActiveRecord::Base

	translates :text

	has_many :requirement_translations
	accepts_nested_attributes_for :requirement_translations

	belongs_to :university

	validates :text, :tution_fee, :university_id, :level, :presence => true

	def level_enum
    {:bsc => "BSc", :msc => "MSc", :phd => "PhD", :preschool => "Pre-school"}
  end

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base

	extend FriendlyId
	friendly_id :first_name, :use => :slugged

	translates :quote, :about, :experience

	has_many :testimonial_translation
	has_many :experience_images
	belongs_to :country

	accepts_nested_attributes_for :testimonial_translation

	belongs_to :university

	mount_uploader :full_image, TestimonialUploader
	mount_uploader :slider_image, TestimonialUploader
	mount_uploader :index_image, TestimonialUploader

	validates :first_name, :last_name, :quote, :about, :university_id, :experience, :presence => true

	def default_for_enum
    I18n.available_locales
  end

end

app/models/text_block.rb
class TextBlock < ActiveRecord::Base

	translates :text, :title

	has_many :text_block_translation
	accepts_nested_attributes_for :text_block_translation

	has_many :medias

	default_scope :order => 'position ASC'

	validates :title, :text, :position, :presence => true
	validates :position, :uniqueness => true

	def default_for_enum
    I18n.available_locales
  end

	def visual_enum
    {:one_col => 1, :two_col => 2, :with_pic => 3, :pic_only => 4}
  end

end

app/models/university.rb
class University < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, :use => :slugged

	translates :description, :campus

	mount_uploader :index_logo, ImageUploader
	mount_uploader :slider_logo, ImageUploader

	has_many :university_translation
	accepts_nested_attributes_for :university_translation

	has_and_belongs_to_many :related_industries
	has_and_belongs_to_many :related_institutions

	has_many :faculties
	has_many :testimonials
	has_many :famous_graduates
	has_many :requirements

	has_many :university_images
	has_many :university_community_images

	validates :name, :short_name, :description, :deadline, :campus, :presence => true

	def default_for_enum
    I18n.available_locales
  end

  # def description
  # 	# self.description.gsub!('#<p[^>]*>(\s|&nbsp;?)*</p>#')
  # 	self.description.downcase!
  # 	# self
  # end

end

app/models/university_image.rb
class UniversityImage < ActiveRecord::Base

	belongs_to :university
	mount_uploader :image_file, UniversityImageUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/wp_blog_post.rb
class WpBlogPost < ActiveRecord::Base

  set_table_name "wp_posts"
  set_primary_key "ID"

  def self.find_by_permalink(year, month, day, title)
    find(:first,
         :conditions => ["YEAR(post_date) = ? AND MONTH(post_date) = ? AND DAYOFMONTH(post_date) = ? AND post_name = ?", year.to_i, month.to_i, day.to_i, title])
  end
end

app/controllers/essentials_controller.rb
class EssentialsController < ApplicationController
  
  def index
    render 'index'
  end
  
end

app/helpers/essentials_helper.rb
module EssentialsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/essentials/_form.html.erb
<%= form_for(@essential) do |f| %>
  <% if @essential.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@essential.errors.count, "error") %> prohibited this essential from being saved:</h2>

      <ul>
      <% @essential.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :topic %><br />
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.number_field :order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/essentials/edit.html.erb
<h1>Editing essential</h1>

<%= render 'form' %>

<%= link_to 'Show', @essential %> |
<%= link_to 'Back', essentials_path %>

app/views/essentials/index.html.erb
<section id="content" class="clearfix">
	<div class="box white-purple twothird">
		<h3>Essentials</h3>
		<p class="left">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer imperdiet mauris eu turpis euismod rutrum dapibus vitae neque. Suspendisse potenti. Mauris eu erat et sapien posuere bibendum at fermentum purus. Fusce molestie ultrices tortor sed tincidunt. Nam at sapien enim, quis vestibulum tortor.
		</p>
		<p class="left">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer imperdiet mauris eu turpis euismod rutrum dapibus vitae neque. Suspendisse potenti. Mauris eu erat et sapien posuere bibendum at fermentum purus. Fusce molestie ultrices tortor sed tincidunt. Nam at sapien enim, quis vestibulum tortor.</p>
	</div>
	<div id="topics" class="third box dark-purple">
		<h4>Topics</h4>
		<ul>
			<li>
				<a href="#visa">Visa</a>
			</li>
			<li>
				<a href="#topic-2">Topic 2</a>
			</li>
			<li>
				<a href="#topic-3">Topic 3</a>
			</li>
			<li>
				<a href="#topic-3">Topic 3</a>
			</li>
			<li>
				<a href="#topic-3">Topic 3</a>
			</li>
			<li>
				<a href="#topic-3">Topic 3</a>
			</li>
		</ul>
	</div>
	<div id="visa" class="clearfix">
		<div class="box third dark-purple">
			<h3>Visa</h3>
			<p>These are the necessary steps for you to get a visa.</p>
		</div>
		<div class="box twothird white">
			<ol>
				<li>Visa application form <p>Mauris eu erat et sapien posuere bibendum at fermentum purus. Fusce molestie ultrices tortor sed tincidunt. Nam at sapien enim, quis vestibulum tortor.</p></li>
				<li>Visa application form <p>Mauris eu erat et sapien posuere bibendum at fermentum purus. Fusce molestie ultrices tortor sed tincidunt. Nam at sapien enim, quis vestibulum tortor.</p></li>
				<li>Visa application form <p>Mauris eu erat et sapien posuere bibendum at fermentum purus. Fusce molestie ultrices tortor sed tincidunt. Nam at sapien enim, quis vestibulum tortor.</p></li>
				<li>Visa application form <p>Mauris eu erat et sapien posuere bibendum at fermentum purus. Fusce molestie ultrices tortor sed tincidunt. Nam at sapien enim, quis vestibulum tortor.</p></li>
				<li>Visa application form <p>Mauris eu erat et sapien posuere bibendum at fermentum purus. Fusce molestie ultrices tortor sed tincidunt. Nam at sapien enim, quis vestibulum tortor.</p></li>
				<li>Visa application form <p>Mauris eu erat et sapien posuere bibendum at fermentum purus. Fusce molestie ultrices tortor sed tincidunt. Nam at sapien enim, quis vestibulum tortor.</p></li>
				<li>Visa application form <p>Mauris eu erat et sapien posuere bibendum at fermentum purus. Fusce molestie ultrices tortor sed tincidunt. Nam at sapien enim, quis vestibulum tortor.</p></li>
				
			</ol>
		</div>
	</div>
</section>

app/views/essentials/new.html.erb
<h1>New essential</h1>

<%= render 'form' %>

<%= link_to 'Back', essentials_path %>

app/views/essentials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Topic:</b>
  <%= @essential.topic %>
</p>

<p>
  <b>Order:</b>
  <%= @essential.order %>
</p>


<%= link_to 'Edit', edit_essential_path(@essential) %> |
<%= link_to 'Back', essentials_path %>